/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Bomba;
import javax.swing.JOptionPane;

/**
 *
 * @author Daryl Ospina
 */
public class FrmPrincipal extends javax.swing.JFrame {

    Bomba bomba1, bomba2;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.btnReiniciar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSegundosBomba1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSegundosBomba2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNegroBomba1 = new javax.swing.JButton();
        btnRojoBomba1 = new javax.swing.JButton();
        btnAzulBomba1 = new javax.swing.JButton();
        btnNegroBomba2 = new javax.swing.JButton();
        btnRojoBomba2 = new javax.swing.JButton();
        btnAzulBomba2 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bomba 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        lblSegundosBomba1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lblSegundosBomba1)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblSegundosBomba1)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bomba 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        lblSegundosBomba2.setText("jlabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(lblSegundosBomba2)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblSegundosBomba2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 0)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP)); // NOI18N

        btnNegroBomba1.setBackground(new java.awt.Color(0, 0, 0));
        btnNegroBomba1.setForeground(new java.awt.Color(255, 255, 255));
        btnNegroBomba1.setText("NEGRO");
        btnNegroBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegroBomba1ActionPerformed(evt);
            }
        });

        btnRojoBomba1.setBackground(new java.awt.Color(255, 0, 0));
        btnRojoBomba1.setForeground(new java.awt.Color(255, 255, 255));
        btnRojoBomba1.setText("ROJO");
        btnRojoBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoBomba1ActionPerformed(evt);
            }
        });

        btnAzulBomba1.setBackground(new java.awt.Color(0, 102, 255));
        btnAzulBomba1.setForeground(new java.awt.Color(255, 255, 255));
        btnAzulBomba1.setText("AZUL");
        btnAzulBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulBomba1ActionPerformed(evt);
            }
        });

        btnNegroBomba2.setBackground(new java.awt.Color(0, 0, 0));
        btnNegroBomba2.setForeground(new java.awt.Color(255, 255, 255));
        btnNegroBomba2.setText("NEGRO");
        btnNegroBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegroBomba2ActionPerformed(evt);
            }
        });

        btnRojoBomba2.setBackground(new java.awt.Color(255, 0, 0));
        btnRojoBomba2.setForeground(new java.awt.Color(255, 255, 255));
        btnRojoBomba2.setText("ROJO");
        btnRojoBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoBomba2ActionPerformed(evt);
            }
        });

        btnAzulBomba2.setBackground(new java.awt.Color(0, 102, 255));
        btnAzulBomba2.setForeground(new java.awt.Color(255, 255, 255));
        btnAzulBomba2.setText("AZUL");
        btnAzulBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulBomba2ActionPerformed(evt);
            }
        });

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("REINICIAR");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNegroBomba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRojoBomba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAzulBomba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNegroBomba2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRojoBomba2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAzulBomba2))
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNegroBomba1)
                    .addComponent(btnRojoBomba1)
                    .addComponent(btnAzulBomba1)
                    .addComponent(btnNegroBomba2)
                    .addComponent(btnRojoBomba2)
                    .addComponent(btnAzulBomba2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("Bomba 2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNegroBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegroBomba1ActionPerformed
        this.bomba1.cortarCable("NEGRO");
    }//GEN-LAST:event_btnNegroBomba1ActionPerformed

    private void btnRojoBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoBomba1ActionPerformed
        this.bomba1.cortarCable("ROJO");
    }//GEN-LAST:event_btnRojoBomba1ActionPerformed

    private void btnAzulBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulBomba1ActionPerformed
        this.bomba1.cortarCable("AZUL");
    }//GEN-LAST:event_btnAzulBomba1ActionPerformed

    private void btnNegroBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegroBomba2ActionPerformed
        this.bomba2.cortarCable("NEGRO");
    }//GEN-LAST:event_btnNegroBomba2ActionPerformed

    private void btnRojoBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoBomba2ActionPerformed
        this.bomba2.cortarCable("ROJO");
    }//GEN-LAST:event_btnRojoBomba2ActionPerformed

    private void btnAzulBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulBomba2ActionPerformed
        this.bomba2.cortarCable("AZUL");
    }//GEN-LAST:event_btnAzulBomba2ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        this.instanciarBombas();
        this.iniciarBombas();
        this.btnIniciar.setEnabled(false);
        this.btnReiniciar.setEnabled(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        this.pararBombas();
        this.instanciarBombas();
        this.iniciarBombas();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzulBomba1;
    private javax.swing.JButton btnAzulBomba2;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnNegroBomba1;
    private javax.swing.JButton btnNegroBomba2;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnRojoBomba1;
    private javax.swing.JButton btnRojoBomba2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblSegundosBomba1;
    private javax.swing.JLabel lblSegundosBomba2;
    // End of variables declaration//GEN-END:variables
    
    public void verificarJuegoGanado(String nombreBomba){
        if (nombreBomba.equalsIgnoreCase(this.bomba1.getName())) {
            if (!this.bomba2.isAlive()) {
                JOptionPane.showMessageDialog(null, "Felicidades!!!, ha ganado el juego");
            }
        }else{
            if (!this.bomba1.isAlive()) {
                JOptionPane.showMessageDialog(null, "Felicidades!!!, ha ganado el juego");
            }
        }
    }
    
    private void instanciarBombas(){
        this.bomba1 = new Bomba("Bomba 1", this.lblSegundosBomba1, this);
        this.bomba2 = new Bomba("Bomba 2", this.lblSegundosBomba2, this);
    }
    
    private void iniciarBombas(){
        this.bomba1.start();
        this.bomba2.start();
    }
    
    public void pararBombas(){
        this.bomba1.interrupt();
        this.bomba2.interrupt();
    }
    
}
